name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install netcat
        run: sudo apt-get update && sudo apt-get install -y netcat

      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 1
          done
          echo "MongoDB is ready!"

      - name: Seed MongoDB
        working-directory: ./eventease-backend
        env:
          MONGO_URI: mongodb://localhost:27017/eventease
        run: |
          npm install
          node seed.js

  test:
    needs: mongo-init
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and run tests
        working-directory: ./eventease-backend
        env:
          MONGO_URI: mongodb://localhost:27017/eventease
        run: |
          npm install
          npm test